#
# PRODUCTION
#
production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  pool: 10
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host: <%= ENV['POSTGRESQL_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRESQL_PORT_5432_TCP_PORT'] %>
  # socket: /tmp/postgresql.sock
